version: '2'
services:

  # ----- uncomment if using postgres --------
  # pl_example_service_postgres:
  #   container_name: "pl_example_service_postgres"
  #   image: "postgres:10.3-alpine"
  #   environment:
  #     POSTGRES_PASSWORD: pass

  # ----- uncomment if using redis --------
  # pl_example_service_redis:
  #   container_name: "pl_example_service_redis"
  #   image: "redis:alpine"

  # ----- comment out if not using rabbitmq --------
  pl_rabbitmq:
    container_name: "pl_rabbitmq"
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
    environment: 
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_VHOST: vhost


  pl_example_service:
    container_name: "pl_example_service"
    build: .
    volumes:
      - .:/home/playola
      - /home/playola/node_modules
    ports:
      - "10020:10020"
    entrypoint: "env-cmd .env nodemon index.js"
    # -- uncomment for services being used
    # depends_on:
    #   - pl_example_service_postgres
    #   - pl_example_service_redis
    #   - pl_rabbitmq
    env_file: .env