version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
        environment:
          - PGHOST: 127.0.0.1
          - PGUSER: root

      - image: circleci/postgres:9.6.2-alpine
        environment:
          - POSTGRES_USER: root
          - POSTGRES_DB: pl_song_importer

      - image: circleci/mongo

      - image: circleci/redis


    working_directory: ~/repo

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init


      # Download and cache dependencies
      - restore_cache:
          keys:
            - pl-song-service-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - pl-song-service-npm-deps-{{ .Branch }}
            - pl-song-service-npm-deps-

      - run: npm install

      - run: npm run migrations

      - save_cache:
          paths:
            - node_modules
          key: pl-song-service-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test

      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
              git push testing master
            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then
              git push staging develop:master
            fi
